# Contributor: Leo <thinkabit.ukim@gmail.com>
# Maintainer:
pkgname=py3-invoke
_pkgname=invoke
pkgver=1.5.0
pkgrel=5
pkgdesc="Pythonic task execution"
options="!check" # Can't find invoke.vendor.six
url="http://docs.pyinvoke.org/en/1.3/"
arch="noarch"
license="BSD-2-Clause"
depends="python3 py3-yaml"
makedepends="py3-setuptools"
source="https://files.pythonhosted.org/packages/source/${_pkgname:0:1}/$_pkgname/$_pkgname-$pkgver.tar.gz
	$pkgname-fix-py311.patch::https://github.com/pyinvoke/invoke/commit/ff9fa16ab8e3ba944c1eb761847b72c6cba6aeca.patch
	"
builddir="$srcdir/$_pkgname-$pkgver"

build() {
	python3 setup.py build
}

package() {
	python3 setup.py install --skip-build --root="$pkgdir"
}

sha512sums="
ac6b1939907ba34930836f567454aeea63373aa510644964eb18e1e684f30d4053c75a73506d0e947a38ca206daf847ce927ec2df15e73932278c2c73c3e20bd  invoke-1.5.0.tar.gz
285b46b73d63ce9d736ad773874a3f4c1dec4c68afabdb1c4ba0c940298243ebd148fe4b7e5558303d14ef1fc5ac3ef305c1d60b6a6c0eb577069fc107fd8532  py3-invoke-fix-py311.patch
"
